### ISSUE TITLE
python-bitcoinrpc

### ISSUE THREAD

**Issue by stephenhoos** [ZeroASIC/eloipool-server#1]
the cloning of bitcoinrpc is failing with a read error.

**Comment by ZeroASIC** [comment]
Is bitcoind in sync with the rest of the network?

**Comment by stephenhoos** [comment]
I was able to fix this by changing the URL to the https link on the github website.

This has nothing to do with bitcoind being synced.  This is clone the git repository during the install process.

**Comment by ZeroASIC** [comment]
Okay, I updated the URLs in the script.  Thanks for the report.
