### ISSUE TITLE
bitcoindata directory

### ISSUE THREAD

**Issue by stephenhoos** [ZeroASIC/eloipool-server#2]
Would it be possible to change the data directory used for bitcoindata to ~/.bitcoin, as this folder holds the blockchain downloaded and confirmed by bitcoin-qt?

**Comment by ZeroASIC** [comment]
You can edit scripts/run-bitcoind.sh so the datadir is pointing to your user directory or remove that line completely if you're running it as your user.

The script is written so it can be run by a user or as a system script.  I tried to keep it flexible enough that it would work anywhere, so it has it's own datadir.
