### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by stephenhoos** [ZeroASIC/eloipool-server#3]
Looks like the install script need to be pointed to the new git repo for midstate.

**Comment by stephenhoos** [comment]
The error occurs during the make of midstate, so this appears to be a midstate problem.

**Comment by ZeroASIC** [comment]
This is the error you sent me:

gcc -march=native -Wall -funroll-all-loops -O3 -fstrict-aliasing -Wall -std=c99 -I/usr/include/python3.2  midstatemodule.c -o test -Wl,-O1 -Wl,--as-needed -lpython3.2mu

midstatemodule.c:5:20: fatal error: Python.h: No such file or directory

compilation terminated.

make: **\* [test] Error 1

It looks like a problem with your python install.

**Comment by stephenhoos** [comment]
kk I think the issue is with the make file.  It looks for python.h in the
/usr/include/pythom3.2 folder and my computer has python3.3  so his
makefile is not up to date for the latest version of python.  I am going to
edit his makefile and test it... I will let you know

**Comment by ZeroASIC** [comment]
Yeah, that's your problem.

**Comment by stephenhoos** [comment]
2.7.4  but his makefile points to python3.2 not python3.3 which is what I
have installed.

**Comment by ZeroASIC** [comment]
Which version of Ubuntu do you have?

**Comment by stephenhoos** [comment]
I have 12.04 and mint 15

**Comment by ZeroASIC** [comment]
My install of Ubuntu 12.04 doesn't have python3.3 available.  I'm going to leave the script as is.
