### ISSUE TITLE
bitcoinrpc.authproxy.JSONRPCException

### ISSUE THREAD

**Issue by macdabby** [ZeroASIC/eloipool-server#4]
I have the software installed on an ubuntu VPS. bitcoin seems to be running fine and has synced the whole chain. 

I started eloipool using run-eloipool.sh

there is an error in the log that im sure is related to my miner not being able to connect - but im not sure which error from bitcoind below is related. i have no idea if this is a configuration error, a version issue, etc.

i appreciate any help with this - i'm happy to contribute but at this time i only have paypal and no bitcoins

This was from the log:
2013-12-05 23:28:16,652 merkleMaker CRITICAL    Traceback (most recent call last):
  File "/etc/eloipool/merklemaker.py", line 692, in run
    self.merkleMaker_I()
  File "/etc/eloipool/merklemaker.py", line 682, in merkleMaker_I
    self.merkleMaker_II()
  File "/etc/eloipool/merklemaker.py", line 648, in merkleMaker_II
    return self._updateMerkleTree()
  File "/etc/eloipool/merklemaker.py", line 548, in _updateMerkleTree
    self._updateMerkleTree_I()
  File "/etc/eloipool/merklemaker.py", line 512, in _updateMerkleTree_I
    r = self._updateMerkleTree_fromTS(TS)
  File "/etc/eloipool/merklemaker.py", line 477, in _updateMerkleTree_fromTS
    MP = self._CallGBT(TS)
  File "/etc/eloipool/merklemaker.py", line 327, in _CallGBT
    MP = access.getblocktemplate(self.GBTReq)
  File "/etc/eloipool/python-bitcoinrpc/bitcoinrpc/authproxy.py", line 116, in __call__
    raise JSONRPCException(response['error'])
bitcoinrpc.authproxy.JSONRPCException

from TCPdump i see these:
request:
POST./.HTTP/1.1
Accept-Encoding:.identity
Content-Length:.68
Host:.localhost
Content-type:.application/json
Authorization:.Basic.####################
User-Agent:
AuthServiceProxy/0.1
{"version":"1.1",."params":[],."method":."getmemorypool","id":.1}

response:
HTTP/1.1
404.Not.Found
Date:.Mon,.06.Jan.2014.03:23:40+0000
Connection:.close
Content-Length:.76
Content-Type:.application/json
Server:.bitcoin-json-rpc/v0.8.5.0-gef14a26-beta
{"result":null,"error":{"code":-32601,"message":"Method.not.found"},"id":1}.

From what I understand this is a version difference error but shouldn't effect eloipool ... i also see :

request: (omitting headers)
{"version":"1.1",."params":[{"capabilities":.["coinbasevalue",."coinbase/append",."coinbase",."generation",."time",."transactions/remove",."prevblock"]}],."method":."getblocktemplate",."id":.1}

response: 
{"result":null,"error":{"code":-10,"message":"Bitcoin.is.downloading.blocks..."},"id":1}

**Comment by ZeroASIC** [comment]
Did you restart the machine and then start the pool again?  You might have too many instances of eloipool running with this error.
